### ISSUE TITLE
無法安裝 electron: 在新环境部署work_crawler时出现的离奇问题

### ISSUE THREAD

**Issue by ha7rock** [kanasimi/work_crawler#104]
```
下載/更新圖形介面需要用到的組件 electron...

> electron@3.0.5 postinstall /home/tetsu76/manga/work_crawler-master/node_module               s/electron
> node install.js

/home/tetsu76/manga/work_crawler-master/node_modules/electron/install.js:49
  throw err
  ^

Error: EACCES: permission denied, mkdir '/home/tetsu76/manga/work_crawler-master               /node_modules/electron/.electron'
npm WARN work_crawler@1.6.20180920 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@3.0.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@3.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log               ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-20T07_43_17_524Z-debug.log
child_process.js:651
    throw err;
    ^

Error: Command failed: npm i -D electron@latest
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:648:13)
    at install_npm (/home/tetsu76/manga/work_crawler.updater.js:62:28)
    at /home/tetsu76/manga/work_crawler.updater.js:90:4
    at /home/tetsu76/manga/GitHub.updater.node.js:87:5
    at recover (/home/tetsu76/manga/GitHub.updater.node.js:327:5)
    at /home/tetsu76/manga/GitHub.updater.node.js:342:4
    at /home/tetsu76/manga/GitHub.updater.node.js:312:4
    at IncomingMessage.<anonymous> (/home/tetsu76/manga/GitHub.updater.node.js:2               78:4)
    at IncomingMessage.emit (events.js:187:15)

```

系统环境： 
Debian9
Node.js ver.10.12
npm 6.4.1

已检查确认档案夹权限没错，可是反复尝试无法成功，看样子是在下载图形化时出错了，请求帮助。

**Comment by kanasimi** [comment]
或許是因為您之前已經用root的身份安裝過
但是現在又用一般使用者的身份來安裝
因此就沒辦法造出檔案夾
'/home/tetsu76/manga/work_crawler-master/node_modules/electron/.electron'

或許您可以試試
把
'/home/tetsu76/manga'
這個資料夾清空之後
重新用一般使用者的身份安裝看看?

當然之前下載過的漫畫得要先備份好

**Comment by ha7rock** [comment]
使用root登入伺服器也是出现同样的错误讯息。真是奇怪呀

**Comment by kanasimi** [comment]
您或許也可以再製造出另外一個目錄
'/home/tetsu76/manga2'
在這個目錄下安裝看看

**Comment by ha7rock** [comment]
```
root@myvps-1:/home/tetsu76/test# npm install -y electron

> electron@3.0.5 postinstall /home/tetsu76/test/node_modules/electron
> node install.js

/home/tetsu76/test/node_modules/electron/install.js:49
  throw err
  ^

Error: EACCES: permission denied, mkdir '/home/tetsu76/test/node_modules/electron/.electron'
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@3.0.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@3.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-20T08_53_28_004Z-debug.log
```

我更换了目录，用手动的方式单独安装electron，还是同样的问题……

**Comment by kanasimi** [comment]
Similar to https://github.com/electron-userland/electron-prebuilt/issues/263 
https://github.com/npm/npm/issues/17268 https://github.com/electron/electron/issues/9815

2 suggests:
1. `sudo npm install -g electron --unsafe-perm=true --allow-root`
2. `sudo ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by ha7rock** [comment]
> Similar to [electron-userland/electron-prebuilt#263](https://github.com/electron-userland/electron-prebuilt/issues/263) [npm/npm#17268](https://github.com/npm/npm/issues/17268) [electron/electron#9815](https://github.com/electron/electron/issues/9815)
> 
> Some suggests:
> 
> 1. Manual install: `npm install electron --save-dev`
> 2. `sudo npm install -g electron --unsafe-perm=true --allow-root`
> 3. `sudo ln -s /usr/bin/nodejs /usr/bin/node`

是的，我原以为已经root登陆了，不再需要sudo，看来还是权限出现了问题
