### ISSUE TITLE
能否新增利用網址下載作品的方式

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#105]
請問能否利用圖片網址去下載圖
http://comics.mrblue.com/MrBlueComicsData_04/webtoon/wt_putringon_wz/22/004.jpg

像是上面的網址只要改成/22/005
就是別下張圖
像是上面的網址只要改成/21/005
就是上一話的第五張圖
能否新增此功能

**Comment by gfhghfghfh** [comment]
http://www.mrblue.com/

**Comment by gfhghfghfh** [comment]
只要改動http://comics.mrblue.com/MrBlueComicsData_04/webtoon/     的後方就可以下載

**Comment by gfhghfghfh** [comment]
好像付費的也可行
能請您增加嗎
不好意思

**Comment by kanasimi** [comment]
抱歉
看不懂韓文
所以不會增加韓文的網站

**Comment by gfhghfghfh** [comment]
不是的
我希望的是利用圖片的網址

**Comment by gfhghfghfh** [comment]
請問不可行嗎

**Comment by kanasimi** [comment]
可以增加這個功能
只是其他網站似乎並沒有這樣子的需求
主要還是以作品的標題為主

**Comment by gfhghfghfh** [comment]
http://comics.mrblue.com/MrBlueComicsData_04/webtoon/A/B/C.jpg
只要藉由改動a b c
就可以下載

懇請您嘗試增加

**Comment by gfhghfghfh** [comment]
在線上作品網站
新增此網站
只不過他的下載方式是透過調動http://comics.mrblue.com/MrBlueComicsData_04/webtoon/A/B/C.jpg
的a b c 來下載
希望您願意採納

**Comment by gfhghfghfh** [comment]
那個因為目前無法用電腦的緣故，我想請問一下，其他網站仍可利用作品名稱或作品id下載沒錯吧
不好意思

**Comment by gfhghfghfh** [comment]
謝謝您

**Comment by gfhghfghfh** [comment]
在請問一下那其他網站利用網址或是作品名稱和作品id ，圖質會有差嗎

**Comment by gfhghfghfh** [comment]
所以說1.利用網址下載2.利用作品名稱和作品id 都是得到＂相同＂的圖質（可獲得的最高品質）嗎？（抱歉，我想問的清楚點）

**Comment by kanasimi** [comment]
yes

**Comment by kanasimi** [comment]
http://comics.mrblue.com/ 要更改的幅度比較大 還不行

**Comment by gfhghfghfh** [comment]
謝謝您的告知，請您慢慢來

**Comment by kanasimi** [comment]
像是這種網站由於很容易被破解
因此恐怕很快就會做出防護
屆時這邊將不再維護
請見諒

**Comment by gfhghfghfh** [comment]
請問能用能圖形介面嗎

**Comment by gfhghfghfh** [comment]
Trace: 本線上作品網站 mrblue 的模組未提供搜尋功能。請手動設定/輸入 [wt_blossom_wz] 之 id 於 mrblue\search.json
 (e.g., {"wt_blossom_wz":""})
    at Work_crawler.onerror (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78:2)), <anonymous>:382:13)
    at Work_crawler.get_work (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78:2)), <anonymous>:1280:9)
    at Work_crawler.parse_work_id (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78:2)), <anonymous>:886:10)
    at Work_crawler.start_downloading [as start] (eval at load_named (eval at <anonymous> (D:\work_crawler-master\CeJS-master\_for include\node.loader.js:78:2)), <anonymous>:727:9)
    at start_crawler (D:\work_crawler-master\work_crawler_loder.js:168:11)
    at Object.<anonymous> (D:\work_crawler-master\comic.cmn-Hans-CN\mrblue.js:82:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

undefined:383
                                throw this.id + ': ' + (new Date).toISOString() + ' ' + error;
                                ^
mrblue: 2018-10-28T03:00:16.955Z 本線上作品網站 mrblue 的模組未提供搜尋功能。請手動設定/輸入 [wt_blossom_wz] 之 id 於 mrblue\search.json
 (e.g., {"wt_blossom_wz":""})

D:\work_crawler-master\comic.cmn-Hans-CN>wt_blossom_wz archive_images=false
'wt_blossom_wz' 不是內部或外部命令、可執行的程式或批次檔。

**Comment by gfhghfghfh** [comment]
我不太清楚如何使用

**Comment by kanasimi** [comment]
請使用
`comic.cmn-Hans-CN>node mrblue.js http://comics.mrblue.com/MrBlueComicsData_04/webtoon/wt_putringon_wz/22/004.jpg`

**Comment by gfhghfghfh** [comment]
修正是指改成可以只打作品id嗎（抱歉現在無法用電腦試

**Comment by kanasimi** [comment]
是的 您可以試試
