### ISSUE TITLE
使用v2ray代理时报错

### ISSUE THREAD

**Issue by Shu-Yibin** [kanasimi/work_crawler#427]
**Version**: v2.8.0懶人安裝法
**Interface**:  命令行界面
部分漫画需要特定地区的IP才能搜索到，在使用v2ray的tls+ws伪装进行连接的时候设定proxy会出现如下报错信息：
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:614:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1527:19)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: 'www.ohmanhua.com',
  port: undefined,
  localAddress: undefined
}

**Comment by kanasimi** [comment]
請問沒設定proxy時可以連接得到嗎

**Comment by kanasimi** [comment]
長時間未回應
關閉議題
