### ISSUE TITLE
您好！第一次尝试下载漫画报错。

### ISSUE THREAD

**Issue by XXieJY** [kanasimi/work_crawler#455]
* **Version**: 懒人安装法
* **Interface**: 命令列介面 
* **Arguments**: 

F:\nodePlayground\work_crawler\comic.cmn-Hans-CN>node 36mh.js "狐妖小红娘"
load_named: [CeL.application.storage.archive] 之初始設定函式執行失敗！
SyntaxError: Unexpected token � in JSON at position 0
36mh: 2020/9/18 17:32:32 开始处理《狐妖小红娘》，储存到 36mh\
从[https://www.36mh.com/js/config.js]取得 1 个图片服务器：https://img001.shmkks.com/
36mh: 已缓存作品 id，不再重新搜寻：狐妖小红娘→"huyaoxiaohongniang"
huyaoxiaohongniang [夏天岛?图：小新,文：小新] 狐妖小红娘: 529 章. 连载中  。  
F:\nodePlayground\work_crawler\node_modules\cejs\application\net\work_crawler\chapter.js:878
                                images_archive = new library_namespace.storage.archive(
                                                 ^

TypeError: library_namespace.storage.archive is not a constructor
    at process_images (F:\nodePlayground\work_crawler\node_modules\cejs\application\net\work_crawler\chapter.js:878:22)
    at Object.process_chapter_data (F:\nodePlayground\work_crawler\node_modules\cejs\application\net\work_crawler\chapter.js:1352:6)
    at Work_crawler.pre_parse_chapter_data (F:\nodePlayground\work_crawler\node_modules\cejs\application\net\work_crawler\sites\SinMH.js:460:4)
    at Work_crawler.pre_parse_chapter_data (F:\nodePlayground\work_crawler\node_modules\cejs\application\net\work_crawler\chapter.js:1367:12)
    at IncomingMessage.<anonymous> (F:\nodePlayground\work_crawler\node_modules\cejs\application\net\Ajax.js:2292:6)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by kanasimi** [comment]
> load_named: [CeL.application.storage.archive] 之初始設定函式執行失敗！

可能是檔案壞了?
改名或刪除 `F:\nodePlayground\work_crawler` 並重新下載工具程式
之後依然無法正常執行的話
請執行 `node 36mh.js "狐妖小红娘" debug=9` 然後貼上執行結果
謝謝

**Comment by XXieJY** [comment]
你好不是档案坏了。
我发现，是我没有成功运行完懒人安装，目前问题已解决。
ps: 我发现如果要使用懒人安装，需要将7zip装载到c:\program files目录下面才行（我觉得你应该更新一下帮助文档）

**Comment by kanasimi** [comment]
> ps: 我发现如果要使用懒人安装，需要将7zip装载到c:\program files目录下面才行（我觉得你应该更新一下帮助文档）

可能是漏掉了 
請問您從哪裡安裝
說明文檔沒有寫到的呢
這邊會再補上

**Comment by XXieJY** [comment]
大概是：https://github.com/kanasimi/work_crawler/blob/master/document/README.cmn-Hans-CN.md#%E6%87%92%E4%BA%BA%E5%AE%89%E8%A3%85%E6%B3%95

**Comment by kanasimi** [comment]
裡面有這句
> 请将程式安装于预设路径下，否则可能出现错误！

由於說明文檔不能加顏色，您覺得怎麼改會比較容易理解呢?

**Comment by XXieJY** [comment]
我个人觉得直接说明 “请将7zip安装于C:/Program Files目录下面”会更好欸
