### ISSUE TITLE
chapter_NO_range用於批量下載時報錯

### ISSUE THREAD

**Issue by gfhghfghfh** [kanasimi/work_crawler#561]
﻿

* **Version**: 
* **Interface**: 
* **Arguments**:

**Comment by gfhghfghfh** [comment]
![image](https://user-images.githubusercontent.com/42042168/175434607-18e7b4d6-6ad5-4596-be13-dfc70277efcc.png)

按下檢查所有最愛作品之更新，並下載更新作品
出現圖中會出現圖中的log

**Comment by gfhghfghfh** [comment]
此外使用命令行版本
使用以下指令也會出現報錯
cd comic.cmn-Hans-CN
node kuaikan 7397 start_chapter=1
node kuaikan 7397 chapter_NO_range=1

**Comment by gfhghfghfh** [comment]
這邊更新後測試
在不同前提下似乎有不同結果


若在初次下載最愛作品清單的情況下
使用chapter_NO_range只有"最愛作品清單編號1"會按照chapter_NO_range的設定

結束最愛作品清單下載後

單獨點擊"最愛作品清單編號2"仍不會依照chapter_NO_range的設定
要將字串內容修改為非20-20才會依照chapter_NO_range的設定



可能是這邊把chapter_NO_range使用前提想得太複雜(可能會這樣使用的人應該沒有?😅
如果您認為這是不必要修正的部分
能麻煩您還是在chapter_NO_range增加說明(像是只用於單次下載不適用於批量)

**Comment by gfhghfghfh** [comment]
此外使用命令行版本
使用以下指令還是會出現報錯
cd comic.cmn-Hans-CN
node kuaikan 7397 start_chapter=1

log內容
_________________________________________________________________________________________________________

D:\Q\work_crawler-master\comic.cmn-Hans-CN>node kuaikan 7397 start_chapter=1
start_chapter: undefined
   由命令列 → 1
kuaikan: 2022/6/25 10:14:52 開始處理《7397》，儲存至 kuaikan\
D:\Q\work_crawler-master\CeJS-master\application\net\work_crawler\work.js:707
                                this.start_chapter_title = this.start_chapter.toLowerCase();
                                                                              ^

TypeError: this.start_chapter.toLowerCase is not a function
    at Work_crawler.get_work_data (D:\Q\work_crawler-master\CeJS-master\application\net\work_crawler\work.js:707:51)
    at Work_crawler.get_work (D:\Q\work_crawler-master\CeJS-master\application\net\work_crawler\work.js:339:9)
    at Work_crawler.parse_work_id (D:\Q\work_crawler-master\CeJS-master\application\net\work_crawler\task.js:636:10)
    at Work_crawler.start_downloading [as start] (D:\Q\work_crawler-master\CeJS-master\application\net\work_crawler\task.js:287:9)
    at start_crawler (D:\Q\work_crawler-master\work_crawler_loader.js:390:10)
    at Object.<anonymous> (D:\Q\work_crawler-master\comic.cmn-Hans-CN\kuaikan.js:132:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

_________________________________________________________________________________________________________














因為這邊覺得是相關的問題因此放在此處
若有不妥請告知
謝謝您
