### ISSUE TITLE
manhuagui连接错误

### ISSUE THREAD

**Issue by MillZou** [kanasimi/work_crawler#587]
﻿

* **Version**: 懶人安裝法
* **Interface**: 命令列介面 on Linux
* **Arguments**: node work_crawler-master/comic.cmn-Hans-CN/manhuagui.js "l=Comics/manhuagui/favorite.txt" --skip_error=true --MIN_LENGTH=40 --allow_EOI_error=true

错误描述：
无法开始下载，Terminal中报出以下错误.

get_URL_node: Exception HTTP status code 406: https://cf.hamreus.com/scripts/core_C0683FDCDEE69940232A703BDEB0F64F.js
get_URL_node: Retry 1/4: BAD STATUS
get_URL_node: Exception HTTP status code 406: https://cf.hamreus.com/scripts/core_C0683FDCDEE69940232A703BDEB0F64F.js
get_URL_node: Retry 2/4: BAD STATUS
get_URL_node: Exception HTTP status code 406: https://cf.hamreus.com/scripts/core_C0683FDCDEE69940232A703BDEB0F64F.js
get_URL_node: Retry 3/4: BAD STATUS
get_URL_node: Exception HTTP status code 406: https://cf.hamreus.com/scripts/core_C0683FDCDEE69940232A703BDEB0F64F.js
get_URL_node: Retry 4/4: BAD STATUS
get_URL_node: Exception HTTP status code 406: https://cf.hamreus.com/scripts/core_C0683FDCDEE69940232A703BDEB0F64F.js
get_URL_node: Got error when retrieving [https://cf.hamreus.com/scripts/core_C0683FDCDEE69940232A703BDEB0F64F.js]: BAD STATUS
work_crawler-master/CeJS-master/application/net/work_crawler/task.js:135
throw typeof error === 'object' ? error : new Error(this.id + ': '
^
Error: manhuagui: 2022/10/30 9:16:39 BAD STATUS
at Work_crawler.onerror (work_crawler-master/CeJS-master/application/net/work_crawler/task.js:135:45)
at Work_crawler.<anonymous> (work_crawler-master/CeJS-master/application/net/work_crawler/task.js:186:11)
at _onfail (work_crawler-master/CeJS-master/application/net/Ajax.js:1814:36)
at IncomingMessage.<anonymous> (work_crawler-master/CeJS-master/application/net/Ajax.js:2227:6)
at IncomingMessage.emit (events.js:326:22)
at endReadableNT (_stream_readable.js:1241:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by kanasimi** [comment]
fixed @ https://github.com/kanasimi/CeJS/commit/3837b30ef790889574ec8ee2021ec419144212c9
