### ISSUE TITLE
convert_to_language not working as expect

### ISSUE THREAD

**Issue by tony1223** [kanasimi/work_crawler#627]
* **Version**: commit 21bf104
* **Interface**: command line
* **Arguments**: 
node .\novel.cmn-Hans-CN\piaotian.js 14341

Expected result:
Translated to zh-TW.

Actual result: 
zh-CN 
===
[第一篇 风起云涌 第一章 许景明](https://www.piaotia.com/html/14/14341/9681165.html)
　　蓝星2081年7月2日13:50，夏国最繁华城市‘滨海市’，此时乌云密布，雷声轰隆，眼看着一场暴雨要来。

　　“夏天的雷阵雨，说来就来。”星空格斗馆顶层的一个房间，一名年轻人正透过落地窗看着外面的乌云闪电，“噼里啪啦”开始有雨滴拍打在窗户玻璃上。

　　年轻人走到房间中央，双手撑地，很缓慢也很稳地进行倒立。先是双手直倒立，后收起了一只手，变成了右手的单手倒立。

**Comment by tony1223** [comment]
I also tried "node .\book.cmn-Hant-TW\epub_hans_to_hant.js xxx.epub", CeL.CN_to_TW seems working but write_file and merge not working properly.

**Comment by tony1223** [comment]
(The os is windows if that matters.)

I did more research.

if i used 
node .\novel.cmn-Hans-CN\piaotian.js 14341 convert_to_language=TW

There's a error as following:
``` 
C:\workspaces\novels\work_crawler\CeJS-master\application\net\work_crawler.js:374
                        && --this.converted_text_cache[options.text]
                                                      ^

TypeError: Cannot read properties of undefined (reading 'requiring_thread_count')
    at Work_crawler.clear_converted_text_cache (C:\workspaces\novels\work_crawler\CeJS-master\application\net\work_crawler.js:374:34)
    at Work_crawler.add_ebook_chapter_actual_work (C:\workspaces\novels\work_crawler\CeJS-master\application\net\work_crawler\ebook.js:1227:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

If I add one line for null protection at work_cralwer.js:373
```
&& this.converted_text_cache[options.text]
```
It seems working on command line now.
